### ISSUE TITLE
Internal Links from <blbl> Tag

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#124]
When a case is cited within a document, and it is a case that we have in the project, can we create an internal link to the Case Page by adding the caseID to the bibl tag like so?

`<bibl type="case" xml:id="oscys.caseid.0011">Queen v. Hepburn</bibl>`

**Comment by karindalziel** [comment]
@kacinash is this done? I'm not sure where to look

**Comment by kacinash** [comment]
@karindalziel No, it is not done. Documents have been encoded with xml:id in bibl tags, like [this one](http://earlywashingtondc.org/doc/oscys.case.0092.005). We need them to link to the cases.

**Comment by karindalziel** [comment]
OK, thinking through the rules for this: 

```XML
<bibl type="case">
5 Hen. & Munfd. 542 6.
<unclear reason="illegible">Samet</unclear>
vs. Saml. & Phillis.
</bibl>
```

```XML
<bibl type="case" xml:id="oscys.caseid.0011">7 Cr. 298 Queen vs Hepburn</bibl>
```

It seems like I would need to match on any bibl type=case which has an xml:id and is in `<text>`.

I'm going to go ahead and give this a shot, but I'm afraid we may see unexpected consequences, so we'll want to check carefully.

**Comment by karindalziel** [comment]
Will be fixed when https://github.com/CDRH/data_oscys/pull/25 is merged
