### ISSUE TITLE
Supplementary Documents that are cases

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#137]
This will probably have to wait until v2. But I noticed that in the cases from Maryland--i.e. category=Supplementary Documents--all of the case documents are showing up under Related Documents because they do not have a category=Case Papers (which we are using for the cases from the DC court). 

See http://rosie.unl.edu/earlywashingtondc/cases/oscys.caseid.0338

In the future, we may want to figure out a way to make the documents for supplementary cases appear under Case Documents instead of Related Documents on their case page.

**Comment by jduss4** [comment]
@kacinash I'm afraid I don't entirely grasp how this issue can be fixed.  Do you know if there are any logical rules we could use to set whether something is a case document or a related document?  I think this would probably need to be changed during the part of the post script that adds documents to caseid files....like maybe if jurisdiction is not DC, then automatically it is a related document or something like that?

**Comment by kacinash** [comment]
Let's just forget about this then.
