### ISSUE TITLE
Case Page - People List shows people from Related Cases

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#155]
When a document is filed in more than one case, the plaintiffs/defendants/attorneys for those related cases are showing up under People. e.g. http://rosie.unl.edu/earlywashingtondc/cases/oscys.caseid.0017

Letitia, Rachel, & Henry Davis are the only plaintiffs for the case, but Ann, David, Sarah, Frederick, Hanson, & George Davis are showing up as well, since they are parties in the other cases in the documents that were filed in more than one case. But shouldn't the People section only be pulling the information in `<listPerson type="oscys.caseid......">` for the matching CaseID?

I don't know if this is something that was working at one time, but isn't now? Not sure if this can be fixed for v1.

**Comment by jduss4** [comment]
The XSLT appears to be grabbing everybody's names, so I will have to fix that so that it's only grabbing by the appropriate case name:

```
<xsl:for-each select="/TEI/teiHeader/profileDesc/particDesc/listPerson/person/persName">
				<xsl:if test="normalize-space(.) != ''">
					<field name="people">
						<xsl:value-of select="."/>
					</field>
				</xsl:if>
			</xsl:for-each>
```

**Comment by jduss4** [comment]
@karindalziel I am scared of this one, too, because you are already doing some things with long comment descriptions of listpersons with caseid or not, though I suspect that the above code is where this particular issue probably needs more to it?

**Comment by karindalziel** [comment]
@jduss4 Honestly I have no idea. We might not be able to get to this issue this week. Really, OSCYS posting needs to be rehauled to address some of this stuff, as we are running into the limitations of the method I was using. I might be able to look a bit later though.

**Comment by jduss4** [comment]
This is addressed in the branch I've been working on which uses ruby to post to solr instead of XSLT!
