### ISSUE TITLE
Images Askew When <p> is Not Closed

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#166]
Images are indenting in documents where `<p>` is open when `<pb facs>` appears. 

See:
http://rosie.unl.edu/earlywashingtondc/doc/oscys.case.0008.001
http://rosie.unl.edu/earlywashingtondc/doc/oscys.case.0017.003

**Comment by karindalziel** [comment]
Fixed! 

http://rosie.unl.edu/earlywashingtondc/doc/oscys.case.0008.001

As always, keep your eye out for more weirdness
