### ISSUE TITLE
Lightbox Isn't Working on CDRHsites

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#174]
The lightbox feature is working on rosie, but on the live site (cdrhsites), it is missing the bounding box that fits the image to the screen, as well as the icons to enlarge and close. 

(Not sure if this is an @jduss4 or @karindalziel issue.)

**Comment by jduss4** [comment]
This seems to be a problem with how the production asset paths differ for images called from libraries (like pretty photo) but I am attempting to confirm.

**Comment by jduss4** [comment]
I am still having trouble with the assets pipeline and the included library prettyPhoto library, but for now I made a workaround.
I will test out including the library as a separate thing in "public" but for now, this is working on cdrhsites.

**Comment by jduss4** [comment]
This seems to be working on production.  Please reopen if that is not the case!
