### ISSUE TITLE
<em> isn't working on CaseID page

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#175]
There are several instances of text in this document that are supposed to be italicized, but the `<em>` tag is apparently not being read, because if you do view source, the tag does not show up.

http://rosie.unl.edu/earlywashingtondc/cases/oscys.caseid.0036

**Comment by karindalziel** [comment]
Could you add some links/docs to look at?

On Thursday, October 15, 2015, Kaci Nash <notifications@github.com> wrote:

> There are several instances of text in this document that are supposed to
> be italicized, but the <em> tag is apparently not being read or converted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CDRH/earlywashingtondc/issues/175>.
>


-- 

----------------------------------------------------------
Karin Dalziel
Digital Design/Development Specialist
Center for Digital Research in the Humanities, University of
Nebraska-Lincoln
kdalziel2@unl.edu
402-472-4547

**Comment by kacinash** [comment]
The link up in the issue is one. Basically any of the Annotated Cases. But especially that http://rosie.unl.edu/earlywashingtondc/cases/oscys.caseid.0036. Every time "<em>In futuro</em>" shows up, there are `<em>` tags around it. Also cases should be italicized too.

**Comment by karindalziel** [comment]
Ah cool, thanks. It wasn't showing up in my email when I checked last
night, sorry!


----------------------------------------------------------
Karin Dalziel
Digital Design/Development Specialist
Center for Digital Research in the Humanities, University of
Nebraska-Lincoln
kdalziel2@unl.edu
402-472-4547

**Comment by karindalziel** [comment]
Changed the <em>s to <hi rend="italic">
