### ISSUE TITLE
lists

### ISSUE THREAD

**Issue by lweakly** [CDRH/earlywashingtondc#177]
This encoding ```xml <list rend="simple"> ``` is displaying with a bullet point before each item. There should not be a bullet point. For an example see: http://earlywashingtondc.org/doc/oscys.mb.0001.007

**Comment by jduss4** [comment]
I'm going to put 
```
.body ul {
	list-style: none;
}
```
in the CSS.  A better solution might be to specifically indicate which lists were "simple" during the transformation from TEI to HTML, but this didn't seem necessary to me.

**Comment by jduss4** [comment]
I am going to wait to rerun the asset compilation on cdrhsites until I can check that things will be okay if the site is down or looks strange for a few minutes.  I may want to test it out on rosie, first, by setting the environment to production.

**Comment by jduss4** [comment]
I believe that this is done!
http://earlywashingtondc.org/doc/oscys.mb.0001.007
