### ISSUE TITLE
oscys.report.0030.001 relationships misidentified

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#179]
I noticed that the attorney relationships that you identified from [oscys.report.0030.001](http://earlywashingtondc.org/doc/oscys.report.0030.001) are backwards. You have [Charles C. Lee](http://earlywashingtondc.org/people/per.001533) as the attorney *against* Gabriel Duvall, when he should be the attorney *for* Duvall. 

Likewise, you have Francis Scott Key as the [Oppositions Attorney to the Butlers](http://earlywashingtondc.org/people/per.001392), when Key was the attorney *for* the Butlers.

For [oscys.report.0030.001](http://earlywashingtondc.org/doc/oscys.report.0030.001), the attorney relationships should be: 
Attorney for Plaintiff(s): Key, Francis Scott, 1779-1843
Attorney for Defendant(s): Jones, Walter, 1776-1861 - Lee, Charles C.

**Comment by lweakly** [comment]
OK. I think I have everyone switched around and committed.

**Comment by kacinash** [comment]
As of right now, these are right in the document encoding, but the relationships are still not correct. I thought we had committed and uploaded the relationships file since this matter was resolved, but maybe not. We will need to check on this the next time the relationships spreadsheet is uploaded.

**Comment by jduss4** [comment]
Is this still unresolved?
