### ISSUE TITLE
Relationships for per.000714

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#180]
The relationships for [per.000714](http://earlywashingtondc.org/people/per.000714) do not seem to be correct. He is a justice of the peace, but he has relationships of 
- Judged By Thruston, Buckner
- Legal Derrick, Matilda
- Slaveholder Of Derrick, Matilda

I think it should just be "Legal Derrick, Matilda" or maybe even perhaps "Witness For Derrick, Matilda," based on the two documents he appears in.

**Comment by lweakly** [comment]
I have deleted the "judgedBy" and "slaveholder of" relationships. I will leave this open so we can check it when we do an update.

**Comment by kacinash** [comment]
As of right now, these are right in the document encoding, but the relationships are still not correct. I thought we had committed and uploaded the relationships file since this matter was resolved, but maybe not. We will need to check on this the next time the relationships spreadsheet is uploaded.
