### ISSUE TITLE
Create Solr Query for Maiden Names

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#182]
We need a `personMaidenName_ss` for the Person Page similar to what we have for Alternate names. We have several women who are known by both their maiden and married names. The display name has their married name, e.g. Allen, Ann, but we also need to account for her maiden name, Turner, for which she is known in half of the documents.

**Comment by karindalziel** [comment]
Curious why the alternate name field can't also be used for maiden names. @lweakly do you have any insights?

I'm also curious how the alternate name field is currently being used.

**Comment by kacinash** [comment]
@karindalziel: The Alternate Name field is used for alternate spellings of the person's name. A person's name is (usually) comprised of <surname> and <forename>. Surname can have a type="maiden" when necessary.

**Comment by lweakly** [comment]
This is the encoding in TEI:

<surname type="maiden">

**Comment by kacinash** [comment]
We will want to discuss how we want to sort and display these names. For example, Ann Turner becomes Ann Allen upon marriage. Should her Display Name be: Turner, Ann? Allen, Ann? Allen, Ann (Turner)?

What about instances where a woman is widowed and remarries. She would have a maiden name and two married names. (I don't think this has happened yet, but it could.)

**Comment by karindalziel** [comment]
Just thinking out loud: 

Perhaps we should change the name of the alternate names field to "alternate spellings" or something like that, and then repurpose the alternate names field for maiden names and other previous names. 

We'll need to play with the display a bit to figure out what works best.

**Comment by kacinash** [comment]
If we're going to do this, it would be great to be able to show `<roleName>` as well. Encoded titles like Capt. and Rev. are not showing up on the site right now.

**Comment by jduss4** [comment]
If I work on this during the week, I am not sure which fields I should be grabbing.  I can include `<roleName>` into all the fields, including maiden, alternate, and traditional names, if you like, but am I using something called `personMaidenName_ss` or something else?

**Comment by kacinash** [comment]
There isn't a solr query at all for this data yet. So you would have to create one. Right now there is only one for Alternate, which is taken from `<addName type="forename" subtype="alternate">`. 

I would like to create (and prioritize) another one for Maiden Name: `<surname type="maiden">`. 

(I am not sure how to tackle people who have multiple surnames, eg: `<persName type="full"> <surname>Blackwell</surname> <surname>Claughton</surname> <surname type="maiden">Routt</surname>, <forename type="first" full="yes">Catherine</forename></persName>`.)

And while we're at it, we should do Title: `<roleName>`.

**Comment by lweakly** [comment]
I'm pretty sure I changed this encoding to <surname type="birth"> to account for those crazy people who had to change their names. It may be just on my branch, though, so we may need to check this. If I need to put attributes on the other surnames, I can do that.

**Comment by jduss4** [comment]
@kacinash right, I understand.  I am sort of wondering what field @karindalziel has in mind for the field stored in solr, because it looked like in the conversation above having a separate maiden name got shot down?

If you have any good examples of people with weird names, I can get started on seeing what sort of thing to pull from it!

**Comment by kacinash** [comment]
I don't know that it got shut down. I think it is a necessary part of the person page.

The aforementioned per.000257 is a good one to start with:

**Catherine Routt (per.000257) has three surnames:**
- maiden: Routt
- marriage 1: Claughton
- marriage 2: Blackwell

**Comment by jduss4** [comment]
Okee dokee!

**Comment by jduss4** [comment]
https://github.com/CDRH/data_oscys/pull/18

**Comment by jduss4** [comment]
@kacinash is this done?  It looked like the PR I referenced above has been completed.

**Comment by kacinash** [comment]
@jduss4 The birth name part was, but not roleName.

**Comment by jduss4** [comment]
@kacinash can you explain what you meant 2 years ago about the roleName not being done?  Can this issue be closed?

**Comment by kacinash** [comment]
We want the roleName encoding to be included on the person page.

**Comment by jduss4** [comment]
Okay, I don't think that is making it into the solr index, yet, so I will need to do a little work there first!

**Comment by jduss4** [comment]
closing with https://github.com/CDRH/earlywashingtondc/commit/e2b54c4099d674a2436ced91ad987a1fa2086824
