### ISSUE TITLE
Claims for Freedom for Case Page

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#183]
We would like to add a new searchable category similar to Outcome and Jurisdiction on the Case Page that indicates the claims for freedom used in the cases. But whereas Outcome and Jurisdiction were pulled from the documents themselves, the Claims will be stored on the Case Page (like related cases is). 
```
<keywords scheme="original" n="claims">
<term>Importation Violation</term>
</keywords>
```

In a few instances, there is more than one claim.
```
<keywords scheme="original" n="claims">
<term>Property Dispute</term>
<term>Term Slavery</term>
</keywords>
```

**Comment by jduss4** [comment]
This work has been completed: https://github.com/CDRH/earlywashingtondc/pull/189
