### ISSUE TITLE
Empty rows on People Index

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#184]
There are two blank rows in the list of people on the [People page](http://earlywashingtondc.org/people/all).

**Comment by jduss4** [comment]
These are the two IDs associated with those blank entries:

http://earlywashingtondc.org/people/per.001839
http://earlywashingtondc.org/people/per.001840

These look to be blank entries in the personography:
https://github.com/CDRH/data/blob/master/projects/oscys/tei/oscys.persons.xml#L17537
https://github.com/CDRH/data/blob/master/projects/oscys/tei/oscys.persons.xml#L17544

**Comment by kacinash** [comment]
Weird. Thanks, @jduss4!
