### ISSUE TITLE
Rework <unclear> and <gap> tags.

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#186]
Previous to our relaunch of the site, the way that we displayed `unclear` tags was for the bracket to appear not around the whole word, but just around the question mark, to indicate that it was an editorial guess. 

![old](https://cloud.githubusercontent.com/assets/6652951/12894846/ecb20c54-ce5e-11e5-89d4-101e63c92292.png)

With the way that it is now--with the brackets surrounding the whole tagged word--I am worried that it isn't easily distinguishable from the `gap` tag, which looks exactly the same, except for the question mark. 

It may not be as critical with `<gap reason="illegible"/>` but it looks awkward with gaps like `<gap reason="ink"/>` or `<gap reason="torn page"/>`.

![ink](https://cloud.githubusercontent.com/assets/6652951/12895013/f5a01d5a-ce5f-11e5-9571-cdc23b2684c4.png)

![torn](https://cloud.githubusercontent.com/assets/6652951/12895009/f1ef2156-ce5f-11e5-9428-dc1598d747fe.png)

I think I would like to make the output of these tags look more distinguishable from each other so that the `gap` reasons do not look like they are `unclear` guesses.

**Comment by jduss4** [comment]
Note to self:  test with oscys.case.0001.009

@kacinash I am a little unclear (not illegible!) on what you would like to change, besides the location of the question mark.

It seems as though gaps will stay the same:
```
<span class="gap illegible">[illegible]</span>
```

However, with unclears, which of the following would you prefer?
```
year 1783<span class="unclear illegible">[?]</span>  # style and brackets on question mark only
year <span class="unclear illegible">1783[?]</span>  # style on date, brackets on question mark
year <span class="unclear illegible">1783[?]</span>  # with different CSS to differentiate span from gap?
```

**Comment by kacinash** [comment]
@jduss4 It's fine that gaps will stay the same. I'd like to figure out way to make the unclears look more visibly different than the gaps, so that "illegible" or "torn image" or "ink" don't look like they are supposed to be interpretations of unclear text. If that makes sense.

I think I would prefer style on date (and the question mark) with only brackets on question mark. So it would look like, when transformed to html, "1783[?]" will be gray.

**Comment by jduss4** [comment]
I believe this is done!  http://rosie.unl.edu/earlywashingtondc/doc/oscys.case.0001.009

**Comment by kacinash** [comment]
@jduss4 Thank you!
