### ISSUE TITLE
If/Then for Relationships Visualization?

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#187]
Per WGT request: Can the script that is generating the relationships visualization do a count? _If_ more than 50 relationships, _then_ only show relationships 1 degree out.

**Comment by jduss4** [comment]
This seems as though it should be doable, though not until the next time we revisit OSCYS.  That's a good idea to help cut down on some of those massively popular people.

**Comment by jduss4** [comment]
This has been implemented!  https://github.com/CDRH/earlywashingtondc/pull/229
