### ISSUE TITLE
Add placeName to Jurisdiction for CCDC cases

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#192]
Since we finally have the cases heard in the Alexandria sittings of the Circuit Court for D.C., we would like to differentiate between the two locations. 

Right now, it just pulls the `<orgName>`, **United States. Circuit Court (District of Columbia)**, from the `<particDesc>`:

```
<listOrg>
<org>
<orgName>United States. Circuit Court (District of Columbia)</orgName>
<placeName>Washington (D.C.)</placeName>
</org>
</listOrg>
```

We would like to be able to include the location in `<placeName>` somehow. Perhaps **United States. Circuit Court (District of Columbia) - Washington (D.C.)** and **United States. Circuit Court (District of Columbia) - Alexandria (Va.)**?

**Comment by jduss4** [comment]
@karindalziel

**Comment by kacinash** [comment]
This has already been done.
