### ISSUE TITLE
EAD notes

### ISSUE THREAD

**Issue by lweakly** [CDRH/earlywashingtondc#193]
Here is an example of the `<note>` that needs styling:

`<c01 level="recordgrp"><did><container type ="box" label="Box">3</container><unitdate type="inclusive" encodinganalog="260" normal="1809">1809, </unitdate>
<unittitle>June, Civil Appearances</unittitle>
<container type="folder" label="Folder">151</container>
<unittitle>Joseph Varden v. John Clay</unittitle> <note><p>sale of "4 Negroes" for $1500 (Clay was from New Orleans, not Washington; laws regulating the sale of slaves in the District probably
complicated this case)</p></note>
</did>
</c01>`

**Comment by jduss4** [comment]
Closing this because it looks like we don't use EAD anywhere and it's only for reference
