### ISSUE TITLE
"1 Related Cases"

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#195]
If we can, we should make some sort of if/then statement for the number of related cases. I just noticed the wording "1 Related Cases" on a [case page](http://earlywashingtondc.org/people/per.000035). Oops.
![screen shot 2016-03-24 at 4 16 31 pm](https://cloud.githubusercontent.com/assets/6652951/14031685/ed4d7342-f1db-11e5-8ab7-aca227063709.png)

**Comment by jduss4** [comment]
I believe this is fixed!
https://github.com/CDRH/earlywashingtondc/commit/0f4675bd31a3dcbbae71acbea23e14f71b31a172
