### ISSUE TITLE
Multiple document subcategories

### ISSUE THREAD

**Issue by jduss4** [CDRH/earlywashingtondc#197]
Stephanie has come across a case document which needs multiple subcategories.  Support for this will need to be built into the data_oscys scripts, solr index (multivalued = true) and into rails.

**Comment by jduss4** [comment]
Currently she encoded both into the TEI but the indexing script is only grabbing the first instance

**Comment by kacinash** [comment]
See [Issue #181](https://github.com/CDRH/earlywashingtondc/issues/181)

**Comment by jduss4** [comment]
Issue #181 has the solution to this problem.  Not only will exhibit types be supported alongside the document subcategories, but multiple subcategories could technically be possible if we changed the posting script xpath
