### ISSUE TITLE
Outcome - don't pull empty field

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#198]
When the outcome is left blank in the TEI header, this happens:
![screen shot 2016-08-22 at 12 57 19 pm](https://cloud.githubusercontent.com/assets/6652951/17865414/1a20d794-6868-11e6-8021-96a43d7d8a79.png)

I went through and deleted all the empties

```
<keywords scheme="original" n="outcome">
<term/>
</keywords>
```

But we might want to fix the code so that this doesn't happen in the future.

**Comment by karindalziel** [comment]
@kacinash when you make an issue, could you always include a link to the page with the issue? Screenshots are also useful, but it would be really nice to be able to follow a link.

**Comment by kacinash** [comment]
@karindalziel I usually do. Except in this case, I went through and removed all of the empty terms, so that it wouldn't show up on the site. The screenshot was the only remnant of the issue.

**Comment by karindalziel** [comment]
@kacinash ah ok. I was wondering why I couldn't find it! this should be fixed soon, and I also accounted for <term>    </term> just in case.

**Comment by karindalziel** [comment]
oops, is already merged haha
