### ISSUE TITLE
"Document" in Document View

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#199]
The info that is being pulled for "Document" category in the Document View has changed somehow. It should be pulling from the `<title>` in the `<bibl>` tag, but instead it is pulling from the one in the `titleStmt`. I am not sure when this change happened, but I am pretty sure at one point it was correct.

**Comment by jduss4** [comment]
I am scared of making this change because I suspect it needs to be changed in multiple places, like in caseRelatedDocumentData fields, etc, so I would be more comfortable with @karindalziel looking at this

**Comment by karindalziel** [comment]
OK, to fix this, what I'll need to do: 

Add a new field, something like source_title

populate this field with something like 

```
/TEI/teiHeader[/fileDesc[1]/sourceDesc[1]/bibl[1]/title[@type='main']
```

And then use that field to populate the following: 

![screen shot 2016-12-21 at 11 45 59 am](https://cloud.githubusercontent.com/assets/284315/21399862/1323f5ce-c773-11e6-938d-f08952365c1f.png)

from page http://rosie.unl.edu/earlywashingtondc/doc/oscys.case.0081.003

@kacinash does the above xpath look correct?

Waiting on getting maiden name in, as I'm afraid of conflicts if we try to add multiple fields at once

**Comment by kacinash** [comment]
@karindalziel Yes, that path looks right.

**Comment by karindalziel** [comment]
@kacinash take a look at these titles: view-source:http://rosie.unl.edu:8983/solr/api_oscys/select?q=*%3A*&rows=0&wt=xml&indent=true&facet=true&facet.field=sourceTitle_s&facet.limit=-1&facet.sort=index&facet.mincount=1

I'll in the meantime change rosie to pull from that field.

**Comment by jduss4** [comment]
@karindalziel is this done?

**Comment by jduss4** [comment]
Closing this until somebody tells me that it's still a problem, appears to be resolved
