### ISSUE TITLE
Rethink/implement indexing system

### ISSUE THREAD

**Issue by karindalziel** [CDRH/earlywashingtondc#201]
The current system is dumb for a couple of reasons:

1: you have to reindex the whole thing every time
2: it creates duplicate multivalued entries

So we need to spend some time to rework. This will likely be a multi day project.

**Comment by jduss4** [comment]
My two cents would be creating something entirely unique from the data repository system.  We could post json then, too, which would make it easier (especially because some of some of the custom "subfields" we're using)

**Comment by karindalziel** [comment]
I think that's a fine idea. Then the data system could be used only for powering the API once it exists and could be simplified a good deal.

**Comment by karindalziel** [comment]
I did a bit of research into this, documenting here

For issue 1: I think we should be able to fix this with some tweaking, but I'm not 100% sure the best route. I have addressed it somewhat in this branch: https://github.com/CDRH/data_oscys/tree/karin_testing where I have removed a bunch of `update=add`'s, but I am getting unexpected results in the final index. For example, case 0430, unlike many of the other cases, didn't seem to get an update from the case files referencing it

(on the left, I manually added one of the cases, neither were present when I first ran the index) 

![screen shot 2017-01-12 at 3 51 29 pm](https://cloud.githubusercontent.com/assets/284315/21909827/297c9696-d8df-11e6-9ba5-f4b3a954bf10.png)

2: There does appear to be a way to mitigate the multivalued queries without reposting the whole thing in solr at least. 

If I run a query like this: 

```XML
<add>
    <doc>
      <field name="id">oscys.caseid.0430</field>
           <field name="TEST_ss" update="removeregex">TEST8</field>
   </doc>
</add>
<add>
    <doc>
      <field name="id">oscys.caseid.0430</field>
           <field name="TEST_ss" update="add">TEST8</field>
   </doc>
</add>
<commit/>
```

the first instance will remove all existing entries for TEST8 and the bottom will re-add it. So this could be a way to restructure the docs and remove duplicate entries. 

HOWEVER, I can't find behavior like the [SOLR Partial Updating](https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents?focusedCommentId=61330220#comment-61330220) in elasticsearch. I think there, we'd need to download the entry, make changes, and readd it whole. There is an [elasticsearch update action](https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html) but it doesn't appear to have all the options solr does.

**Comment by karindalziel** [comment]
A little more research: if the case files happen to run BEFORE the caseID files, the info is wiped out. I might be able to fix this, or we might need to always run the caseid's first?

**Comment by karindalziel** [comment]
OK, final bit of info here before I stop this for now (since I don't know how the API will affect it) 

I added this field to the index: `<field name="update_increment_i" update="inc">1</field>`

For the caseid filed, this will increment every time new info is posted so we can see how many times the document has been added to. So a caseid with three documents would be set like this at the end of running the index: `<int name="update_increment_i">4</int>`

I added this because for some reason it stops a caseid file from erasing previous info when run. So, previously, if you ran the case documents and then the caseid file, it would erase all the documents info. Adding an increment or `update='add'` stops this behavior. 

I have not yet worked on mitigating duplicates, however, so we will still want to clear and rerun occasionally. 

I believe it won't be too hard to remove duplicates using the method above, but I want to wait until we figure out API/elasticsearch stuff.

**Comment by karindalziel** [comment]
Part of this will be taken care of by https://github.com/CDRH/data_oscys/pull/24

Perhaps after that's merged we should start a new issue re: duplicate multivalued fields

**Comment by karindalziel** [comment]
I scheduled a week to take care of this once and for all in Feb of 2019. 

Likely the answer will be "make it a database"

**Comment by jduss4** [comment]
THIS IS SUPER DONE AND VERY FANTASTIC
