### ISSUE TITLE
bibl italics are not working for all

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#213]
In the case narratives/summaries, the `bibl` tags are not all going italic like they should.

[Example](http://earlywashingtondc.org/cases/oscys.caseid.0092):
![screen shot 2017-04-26 at 4 50 44 pm](https://cloud.githubusercontent.com/assets/6652951/25458691/842fd2de-2aa0-11e7-80ec-1d2345a24b03.png)

Code:
`<bibl type="treatise">Reports of Cases Civil and Criminal in the United States Circuit Court of the District of Columbia, from 1801 to 1841</bibl>`

**Comment by jduss4** [comment]
Added https://github.com/CDRH/earlywashingtondc/commit/fc350d69d3fc04fea37f5b80bf582e0b552122a7

Also builds on `<span class="italic">` which was not previously being italicized.  Now both should be!  Let me know if they look good, @kacinash , and I can push to master.

Same link above but on dev:  https://cdrhdev1.unl.edu/earlywashingtondc/cases/oscys.caseid.0092

**Comment by kacinash** [comment]
The linked case works. In that instance, it was encoded `bibl type="treatise"`. Also works [here](https://cdrhdev1.unl.edu/earlywashingtondc/cases/oscys.caseid.0251) where it was encoded with `hi rend="italic"` (I'm not sure why it was ever done like that instead of bibl.)

But it's not working [here](https://cdrhdev1.unl.edu/earlywashingtondc/cases/oscys.caseid.0337) where it's encoded `bibl type="case"`. That should be italics too.

**Comment by jduss4** [comment]
@kacinash I'll add that to the styling this afternoon and let you know!

**Comment by jduss4** [comment]
@kacinash I added the cases, too!  I will wait to pull anything to production today, I think I need to recompile the assets to get it to see the new css change, which seems like a better morning activity :)

**Comment by jduss4** [comment]
@kacinash I deployed this to production this morning!  Let me know if the cases, italics, and treatises all look good to you and feel free to close this issue, if so!

**Comment by kacinash** [comment]
Thanks, @jduss4.
