### ISSUE TITLE
Relationship information/visualization currently unavailable

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#214]
I came across some random people whose relationship information is apparently unavailable. I'm not sure what is causing this error.

It is many of the participants in [case 36](http://earlywashingtondc.org/cases/oscys.caseid.0036), but strangely, not all of them. The parties and attorneys are ok. See, for example:
http://earlywashingtondc.org/people/per.000336
http://earlywashingtondc.org/people/per.000354
http://earlywashingtondc.org/people/per.000296
http://earlywashingtondc.org/people/per.000411

I can't find any other people with this problem outside of those for case 36, so it seems to be an isolated instance. **EDITED** Looks like it's not just with this case. See:
http://earlywashingtondc.org/people/per.000126
http://earlywashingtondc.org/people/per.000129
http://earlywashingtondc.org/people/per.000905

**Comment by jduss4** [comment]
This appears to be because those people do not have relationships.  Code updated to display error if RDF is actually down or hide the column if there are no people found:

https://github.com/CDRH/earlywashingtondc/commit/130862e81c99a4940a00c6f936f27c9cb4ad6ee9
