### ISSUE TITLE
transformation for <gap> tag has randomly changed

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#219]
For some reason, it looks like the formatting for the `gap` tag has randomly changed. 

http://earlywashingtondc.org/doc/oscys.case.0076.005
![screen shot 2017-12-13 at 1 20 09 pm](https://user-images.githubusercontent.com/6652951/33957839-61781a80-e008-11e7-9015-c5023f118f34.png)

The **[reason]** has previously always appeared grey in color, but for some reason, this has recently changed. See image in #186.

**Comment by jduss4** [comment]
I'm guessing this is related to some of the general work @karindalziel has done on the shared scripts?  Will need to look into it more.

**Comment by kacinash** [comment]
I don't know what caused this issue, but I was able to work around it by adding some classes to the css.
