### ISSUE TITLE
add ref type related.doc

### ISSUE THREAD

**Issue by kacinash** [CDRH/earlywashingtondc#220]
I would like to add a `<ref type="related.doc">` that works the same what as `<ref type="related.case">`.

**Comment by jduss4** [comment]
@kacinash so this would mean we would need to add a section of the documents page that linked to related documents?  It's doable, we would just need to add a few fields to the solr index, then populate them, then add a section to the website to display them.

**Comment by kacinash** [comment]
I'm not sure where I was going with this request. I think it was probably just for in text links, but I wouldn't worry about this one. I think we can delete it.

On Wed, Mar 27, 2019, 9:20 AM Jessica Dussault <notifications@github.com<mailto:notifications@github.com>> wrote:

@kacinash<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kacinash&d=DwMCaQ&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=mVduhkIA9-iM5qs4Z00Vcw&m=jGmmd_nGYDzHsD4J1AhtMynJhvj4_3NNwupZttF3aIw&s=UeQzqeRI5nrRVFxWhM28hauYj1BfAcTF0qxIlHvSRtA&e=> so this would mean we would need to add a section of the documents page that linked to related documents? It's doable, we would just need to add a few fields to the solr index, then populate them, then add a section to the website to display them.

**Comment by jduss4** [comment]
Awesome!  :)
