### ISSUE TITLE
Improvements to visualizations

### ISSUE THREAD

**Issue by karindalziel** [CDRH/earlywashingtondc#36]
Just getting these down to discuss - not all of these need to be implemented. 

I will be splitting these into actual issues later as needed, but feel free to chip in with comments and observations. 
- Remember that by launch, we should comment out the magenta lines.  Probably just color those black in case any more errors show up. 
- Flow of the visualizations into one another: I'd like to sit down and think about how people might actually use this, and the best way to make that obvious. For instance, right now, it's not super clear that clicking a person changes the sidebar to include a link to that person's page. Once you get the hang of it it is not hard, but it is not intuitive. 
  - similarly, I think a link from within the visualization should take you to that person's visualization, rather than the person's history page.  (DONE!)
- I'd like to think about the wording to get back to the in template person view. Right now it says "Back to person view" but I don't think that's especially clear, since the visualization looks like it IS a person view. 
- we need to fix the "Limit relationships by" section to match up with the relationship types (DONE)
- It would be nice if we could only show the relationships a person actually has, but failing that, we should have a nicer view when someone has no relationships of that type (e.g. http://rosie.unl.edu/earlywashingtondc/people/network/per.000194?type=familyOf). Maybe it will just say "no relationships" or something.  (DONE)

**Comment by jduss4** [comment]
I am closing this issue because it seems like it was from development.  New issues with visualizations can live in their own issues.
