### ISSUE TITLE
Things I wish I could answer on the site

### ISSUE THREAD

**Issue by karindalziel** [CDRH/earlywashingtondc#37]
For v2, I just have these on the brain as things I'd like to be able to get out of the data. Maybe we could create some of these for the stories section?
- get a list of all the slaveowners and visualize
- get a list of all slaves and visualize
- visualization of subsets - for instance, all the people involved in a particular case
- given a list of people visualize the relationships between them. 

There's tons more, add ideas here!

**Comment by jduss4** [comment]
in terms of creating lists of slaves and slaveholders, etc, the RDF queries already have accomplished that.  Do we want to close this issue?

**Comment by karindalziel** [comment]
@jduss4 would people (the general public)  be able to actually generate these visualizations?

**Comment by karindalziel** [comment]
I should probably have a milestone that's "ideas to think about when we have another OSCYS sprint" or something

**Comment by jduss4** [comment]
Oh I see, I misunderstood what this was asking.  other than seeing the slaveholders and slaves on the visualization pages (with their relationships marked), you cannot just browse this as a whole visualization.  It would definitely be an interesting feature, though, maybe under stories?

**Comment by karindalziel** [comment]
@jduss4  yeah, but this is definitely not something we need to tackle in bug squash week.

**Comment by karindalziel** [comment]
@jduss4 I think for the purposes of bug squash weeks, you can probably ignore anything marked "notes" and maybe we should discuss better ways of handling these things in a dev meeting. Maybe move these things to a wiki or something.

**Comment by jduss4** [comment]
okay!

**Comment by jduss4** [comment]
As these issues are several years old and no moves have been made to work towards these types of visualizations / questions, I am going to close them
