### ISSUE TITLE
Rethink search

### ISSUE THREAD

**Issue by karindalziel** [CDRH/earlywashingtondc#84]
I think we could rethink search and improve it in some ways:
- more facets, easier way to add facets? (more like blacklight)
- getting rid of un-useful options (i.e. relevance sort when the relevance will be the same for every item)

**Comment by jduss4** [comment]
I'm going to close this for now because it seems unlikely, unless if the site is powered by elasticsearch / orchid, that we are going to be putting substantial work into this via solr
